name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  CSV_URL: "MLProject/diabetes_clean.csv"
  TARGET_VAR: "Outcome"

jobs:
  ci-mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLFlow Project
        run: |
          mlflow run MLProject --env-manager=local

      - name: Get latest MLFlow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload ML Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-model-artifact
          path: mlruns/0/${{ env.RUN_ID }}/artifacts/model

      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "diabetes-prediction-model"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag diabetes-prediction-model ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-prediction-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-prediction-model:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push to GitHub Packages
        run: |
          OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          docker tag diabetes-prediction-model ghcr.io/${OWNER_LOWER}/diabetes-prediction-model:latest
          docker push ghcr.io/${OWNER_LOWER}/diabetes-prediction-model:latest
