name: Train and Deploy Diabetes Model

on:
  push:
    paths:
      - "MLProject/**"
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12.7
          environment-file: MLProject/conda.yaml
          activate-environment: diabetes-env

      - name: Install MLflow CLI
        run: pip install mlflow

      - name: Run MLflow Project (Train Model)
        run: |
          cd MLProject
          mlflow run . -P data_path=diabetes_clean.csv

      - name: Find Latest Run ID
        id: get-run-id
        run: |
          RUN_ID=$(ls ~/.mlflow/mlruns/0 | tail -n 1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Save MLflow Artifacts
        run: |
          mkdir -p mlruns_artifacts
          cp -r ~/.mlflow/mlruns mlruns_artifacts/

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns_artifacts

      - name: Build Docker Image from MLflow Model
        run: |
          cd ~/.mlflow/mlruns/0/${{ steps.get-run-id.outputs.run_id }}/artifacts/model
          mlflow models build-docker -n diabetes_model

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag diabetes_model ${{ secrets.DOCKER_USERNAME }}/diabetes_model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/diabetes_model:latest
